// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/auth/domain/use_cases/signup_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_app/core/api/models/requests/user_request.dart' as _i9;
import 'package:flower_app/core/error_handling/result.dart' as _i4;
import 'package:flower_app/features/auth/data/models/requests/change_password_request.dart'
    as _i14;
import 'package:flower_app/features/auth/data/models/response/change_password_response.dart'
    as _i13;
import 'package:flower_app/features/auth/data/models/response/reset_password_response.dart'
    as _i12;
import 'package:flower_app/features/auth/data/models/response/send_reset_password_code_response.dart'
    as _i10;
import 'package:flower_app/features/auth/data/models/response/verify_reset_code_response.dart'
    as _i11;
import 'package:flower_app/features/auth/data/models_dto/login/login_request.dart'
    as _i6;
import 'package:flower_app/features/auth/data/models_dto/login/login_response_dto.dart'
    as _i5;
import 'package:flower_app/features/auth/domain/models/user_entity.dart' as _i8;
import 'package:flower_app/features/auth/domain/repositories/auth_repo.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepo extends _i1.Mock implements _i2.AuthRepo {
  MockAuthRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.LoginResponseDto>> login({
    required _i6.LoginRequest? loginRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#loginRequest: loginRequest}),
            returnValue: _i3.Future<_i4.Result<_i5.LoginResponseDto>>.value(
              _i7.dummyValue<_i4.Result<_i5.LoginResponseDto>>(
                this,
                Invocation.method(#login, [], {#loginRequest: loginRequest}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.LoginResponseDto>>);

  @override
  _i3.Future<_i4.Result<_i8.UserEntity>> signUp(
    _i9.UserSignupRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [request]),
            returnValue: _i3.Future<_i4.Result<_i8.UserEntity>>.value(
              _i7.dummyValue<_i4.Result<_i8.UserEntity>>(
                this,
                Invocation.method(#signUp, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.UserEntity>>);

  @override
  _i3.Future<_i4.Result<_i10.SendResetPasswordCodeResponse>>
  sendResetPasswordCode({required String? email}) =>
      (super.noSuchMethod(
            Invocation.method(#sendResetPasswordCode, [], {#email: email}),
            returnValue:
                _i3.Future<
                  _i4.Result<_i10.SendResetPasswordCodeResponse>
                >.value(
                  _i7.dummyValue<
                    _i4.Result<_i10.SendResetPasswordCodeResponse>
                  >(
                    this,
                    Invocation.method(#sendResetPasswordCode, [], {
                      #email: email,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i10.SendResetPasswordCodeResponse>>);

  @override
  _i3.Future<_i4.Result<_i11.VerifyResetCodeResponse>> verifyResetPasswordCode({
    required String? resetCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetPasswordCode, [], {
              #resetCode: resetCode,
            }),
            returnValue:
                _i3.Future<_i4.Result<_i11.VerifyResetCodeResponse>>.value(
                  _i7.dummyValue<_i4.Result<_i11.VerifyResetCodeResponse>>(
                    this,
                    Invocation.method(#verifyResetPasswordCode, [], {
                      #resetCode: resetCode,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i11.VerifyResetCodeResponse>>);

  @override
  _i3.Future<_i4.Result<_i12.ResetPasswordResponse>> resetPassword({
    required String? email,
    dynamic password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i3.Future<_i4.Result<_i12.ResetPasswordResponse>>.value(
                  _i7.dummyValue<_i4.Result<_i12.ResetPasswordResponse>>(
                    this,
                    Invocation.method(#resetPassword, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i12.ResetPasswordResponse>>);

  @override
  _i3.Future<_i4.Result<_i13.ChangePasswordResponse>> changePassword({
    required _i14.ChangePasswordRequest? changePasswordRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #changePasswordRequest: changePasswordRequest,
            }),
            returnValue:
                _i3.Future<_i4.Result<_i13.ChangePasswordResponse>>.value(
                  _i7.dummyValue<_i4.Result<_i13.ChangePasswordResponse>>(
                    this,
                    Invocation.method(#changePassword, [], {
                      #changePasswordRequest: changePasswordRequest,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i13.ChangePasswordResponse>>);
}
