// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/auth/data/datasources/auth_ds_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i14;

import 'package:flower_app/core/api/api_client.dart' as _i13;
import 'package:flower_app/core/api/models/requests/user_request.dart' as _i16;
import 'package:flower_app/core/api/models/response/signup_response.dart'
    as _i3;
import 'package:flower_app/core/app/data/models/product_response.dart' as _i8;
import 'package:flower_app/core/error_handling/base_response_result_dto.dart'
    as _i12;
import 'package:flower_app/features/auth/data/models/requests/reset_password_request.dart'
    as _i19;
import 'package:flower_app/features/auth/data/models/requests/send_reset_password_code_request.dart'
    as _i17;
import 'package:flower_app/features/auth/data/models/requests/verify_reset_code_request.dart'
    as _i18;
import 'package:flower_app/features/auth/data/models/response/reset_password_response.dart'
    as _i6;
import 'package:flower_app/features/auth/data/models/response/send_reset_password_code_response.dart'
    as _i4;
import 'package:flower_app/features/auth/data/models/response/verify_reset_code_response.dart'
    as _i5;
import 'package:flower_app/features/auth/data/models_dto/login/login_request.dart'
    as _i15;
import 'package:flower_app/features/auth/data/models_dto/login/login_response_dto.dart'
    as _i2;
import 'package:flower_app/features/categories/data/models/categories_response.dart'
    as _i9;
import 'package:flower_app/features/home/data/models/best_seller_response.dart'
    as _i7;
import 'package:flower_app/features/home/data/models/home_response_dto.dart'
    as _i10;
import 'package:flower_app/features/orders/data/models/cart_request_dto.dart'
    as _i20;
import 'package:flower_app/features/orders/data/models/order_response_dto.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponseDto_0 extends _i1.SmartFake
    implements _i2.LoginResponseDto {
  _FakeLoginResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSignupResponse_1 extends _i1.SmartFake
    implements _i3.SignupResponse {
  _FakeSignupResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSendResetPasswordCodeResponse_2 extends _i1.SmartFake
    implements _i4.SendResetPasswordCodeResponse {
  _FakeSendResetPasswordCodeResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeVerifyResetCodeResponse_3 extends _i1.SmartFake
    implements _i5.VerifyResetCodeResponse {
  _FakeVerifyResetCodeResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponse_4 extends _i1.SmartFake
    implements _i6.ResetPasswordResponse {
  _FakeResetPasswordResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBestSellerResponse_5 extends _i1.SmartFake
    implements _i7.BestSellerResponse {
  _FakeBestSellerResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductResponse_6 extends _i1.SmartFake
    implements _i8.ProductResponse {
  _FakeProductResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoriesResponse_7 extends _i1.SmartFake
    implements _i9.CategoriesResponse {
  _FakeCategoriesResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeResponseDto_8 extends _i1.SmartFake
    implements _i10.HomeResponseDto {
  _FakeHomeResponseDto_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCartResponseDto_9 extends _i1.SmartFake
    implements _i11.CartResponseDto {
  _FakeCartResponseDto_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSuccessResponseDto_10 extends _i1.SmartFake
    implements _i12.SuccessResponseDto {
  _FakeSuccessResponseDto_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i13.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.Future<_i2.LoginResponseDto> login({
    required _i15.LoginRequest? loginRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#loginRequest: loginRequest}),
            returnValue: _i14.Future<_i2.LoginResponseDto>.value(
              _FakeLoginResponseDto_0(
                this,
                Invocation.method(#login, [], {#loginRequest: loginRequest}),
              ),
            ),
          )
          as _i14.Future<_i2.LoginResponseDto>);

  @override
  _i14.Future<_i3.SignupResponse> signUp(_i16.UserSignupRequest? userRequest) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [userRequest]),
            returnValue: _i14.Future<_i3.SignupResponse>.value(
              _FakeSignupResponse_1(
                this,
                Invocation.method(#signUp, [userRequest]),
              ),
            ),
          )
          as _i14.Future<_i3.SignupResponse>);

  @override
  _i14.Future<_i4.SendResetPasswordCodeResponse> sendResetPasswordCode({
    required _i17.SendResetPasswordCodeRequest? sendResetPasswordCodeRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendResetPasswordCode, [], {
              #sendResetPasswordCodeRequest: sendResetPasswordCodeRequest,
            }),
            returnValue: _i14.Future<_i4.SendResetPasswordCodeResponse>.value(
              _FakeSendResetPasswordCodeResponse_2(
                this,
                Invocation.method(#sendResetPasswordCode, [], {
                  #sendResetPasswordCodeRequest: sendResetPasswordCodeRequest,
                }),
              ),
            ),
          )
          as _i14.Future<_i4.SendResetPasswordCodeResponse>);

  @override
  _i14.Future<_i5.VerifyResetCodeResponse> verifyResetPasswordCode({
    required _i18.VerifyResetCodeRequest? verifyResetCodeRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetPasswordCode, [], {
              #verifyResetCodeRequest: verifyResetCodeRequest,
            }),
            returnValue: _i14.Future<_i5.VerifyResetCodeResponse>.value(
              _FakeVerifyResetCodeResponse_3(
                this,
                Invocation.method(#verifyResetPasswordCode, [], {
                  #verifyResetCodeRequest: verifyResetCodeRequest,
                }),
              ),
            ),
          )
          as _i14.Future<_i5.VerifyResetCodeResponse>);

  @override
  _i14.Future<_i6.ResetPasswordResponse> resetPassword({
    required _i19.ResetPasswordRequest? resetPasswordRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #resetPasswordRequest: resetPasswordRequest,
            }),
            returnValue: _i14.Future<_i6.ResetPasswordResponse>.value(
              _FakeResetPasswordResponse_4(
                this,
                Invocation.method(#resetPassword, [], {
                  #resetPasswordRequest: resetPasswordRequest,
                }),
              ),
            ),
          )
          as _i14.Future<_i6.ResetPasswordResponse>);

  @override
  _i14.Future<_i7.BestSellerResponse> getBestSeller() =>
      (super.noSuchMethod(
            Invocation.method(#getBestSeller, []),
            returnValue: _i14.Future<_i7.BestSellerResponse>.value(
              _FakeBestSellerResponse_5(
                this,
                Invocation.method(#getBestSeller, []),
              ),
            ),
          )
          as _i14.Future<_i7.BestSellerResponse>);

  @override
  _i14.Future<_i8.ProductResponse> getProducts({
    String? occasionId,
    String? categoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {
              #occasionId: occasionId,
              #categoryId: categoryId,
            }),
            returnValue: _i14.Future<_i8.ProductResponse>.value(
              _FakeProductResponse_6(
                this,
                Invocation.method(#getProducts, [], {
                  #occasionId: occasionId,
                  #categoryId: categoryId,
                }),
              ),
            ),
          )
          as _i14.Future<_i8.ProductResponse>);

  @override
  _i14.Future<_i9.CategoriesResponse> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i14.Future<_i9.CategoriesResponse>.value(
              _FakeCategoriesResponse_7(
                this,
                Invocation.method(#getCategories, []),
              ),
            ),
          )
          as _i14.Future<_i9.CategoriesResponse>);

  @override
  _i14.Future<_i10.HomeResponseDto> fetchHomeData() =>
      (super.noSuchMethod(
            Invocation.method(#fetchHomeData, []),
            returnValue: _i14.Future<_i10.HomeResponseDto>.value(
              _FakeHomeResponseDto_8(
                this,
                Invocation.method(#fetchHomeData, []),
              ),
            ),
          )
          as _i14.Future<_i10.HomeResponseDto>);

  @override
  _i14.Future<_i11.CartResponseDto> addProductToCart(
    _i20.CartRequestDto? cartRequestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addProductToCart, [cartRequestDto]),
            returnValue: _i14.Future<_i11.CartResponseDto>.value(
              _FakeCartResponseDto_9(
                this,
                Invocation.method(#addProductToCart, [cartRequestDto]),
              ),
            ),
          )
          as _i14.Future<_i11.CartResponseDto>);

  @override
  _i14.Future<_i11.CartResponseDto> removeProductFromCart(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeProductFromCart, [id]),
            returnValue: _i14.Future<_i11.CartResponseDto>.value(
              _FakeCartResponseDto_9(
                this,
                Invocation.method(#removeProductFromCart, [id]),
              ),
            ),
          )
          as _i14.Future<_i11.CartResponseDto>);

  @override
  _i14.Future<_i12.SuccessResponseDto> clearCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, []),
            returnValue: _i14.Future<_i12.SuccessResponseDto>.value(
              _FakeSuccessResponseDto_10(
                this,
                Invocation.method(#clearCart, []),
              ),
            ),
          )
          as _i14.Future<_i12.SuccessResponseDto>);

  @override
  _i14.Future<_i11.CartResponseDto> getLoggedUserCart() =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedUserCart, []),
            returnValue: _i14.Future<_i11.CartResponseDto>.value(
              _FakeCartResponseDto_9(
                this,
                Invocation.method(#getLoggedUserCart, []),
              ),
            ),
          )
          as _i14.Future<_i11.CartResponseDto>);

  @override
  _i14.Future<_i11.CartResponseDto> updateProductQuantity(
    String? id,
    Map<String, int>? quantity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProductQuantity, [id, quantity]),
            returnValue: _i14.Future<_i11.CartResponseDto>.value(
              _FakeCartResponseDto_9(
                this,
                Invocation.method(#updateProductQuantity, [id, quantity]),
              ),
            ),
          )
          as _i14.Future<_i11.CartResponseDto>);
}
