// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/auth/data/datasources/auth_ds_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i19;

import 'package:dio/dio.dart' as _i28;
import 'package:flower_app/core/api/api_client.dart' as _i18;
import 'package:flower_app/core/api/models/requests/user_request.dart' as _i21;
import 'package:flower_app/core/api/models/response/signup_response.dart'
    as _i3;
import 'package:flower_app/core/app/data/models/product_response.dart' as _i9;
import 'package:flower_app/core/app/data/models/response/get_current_user_data_response_dto.dart'
    as _i7;
import 'package:flower_app/core/error_handling/base_response_result_dto.dart'
    as _i14;
import 'package:flower_app/features/auth/data/models/requests/change_password_request.dart'
    as _i26;
import 'package:flower_app/features/auth/data/models/requests/reset_password_request.dart'
    as _i24;
import 'package:flower_app/features/auth/data/models/requests/send_reset_password_code_request.dart'
    as _i22;
import 'package:flower_app/features/auth/data/models/requests/verify_reset_code_request.dart'
    as _i23;
import 'package:flower_app/features/auth/data/models/response/change_password_response.dart'
    as _i15;
import 'package:flower_app/features/auth/data/models/response/reset_password_response.dart'
    as _i6;
import 'package:flower_app/features/auth/data/models/response/send_reset_password_code_response.dart'
    as _i4;
import 'package:flower_app/features/auth/data/models/response/verify_reset_code_response.dart'
    as _i5;
import 'package:flower_app/features/auth/data/models_dto/login/login_request.dart'
    as _i20;
import 'package:flower_app/features/auth/data/models_dto/login/login_response_dto.dart'
    as _i2;
import 'package:flower_app/features/auth/data/models_dto/logout/logout_response_dto.dart'
    as _i12;
import 'package:flower_app/features/categories/data/models/categories_response.dart'
    as _i10;
import 'package:flower_app/features/home/data/models/best_seller_response.dart'
    as _i8;
import 'package:flower_app/features/home/data/models/home_response_dto.dart'
    as _i11;
import 'package:flower_app/features/orders/data/models/cart_request_dto.dart'
    as _i25;
import 'package:flower_app/features/orders/data/models/order_response_dto.dart'
    as _i13;
import 'package:flower_app/features/profile/data/models/edit_profile_request.dart'
    as _i27;
import 'package:flower_app/features/profile/data/models/get_user_data_response.dart'
    as _i16;
import 'package:flower_app/features/profile/data/models/upload_photo_response.dart'
    as _i17;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLoginResponseDto_0 extends _i1.SmartFake
    implements _i2.LoginResponseDto {
  _FakeLoginResponseDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSignupResponse_1 extends _i1.SmartFake
    implements _i3.SignupResponse {
  _FakeSignupResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSendResetPasswordCodeResponse_2 extends _i1.SmartFake
    implements _i4.SendResetPasswordCodeResponse {
  _FakeSendResetPasswordCodeResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeVerifyResetCodeResponse_3 extends _i1.SmartFake
    implements _i5.VerifyResetCodeResponse {
  _FakeVerifyResetCodeResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponse_4 extends _i1.SmartFake
    implements _i6.ResetPasswordResponse {
  _FakeResetPasswordResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetCurrentUserDataResponseDto_5 extends _i1.SmartFake
    implements _i7.GetCurrentUserDataResponseDto {
  _FakeGetCurrentUserDataResponseDto_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeBestSellerResponse_6 extends _i1.SmartFake
    implements _i8.BestSellerResponse {
  _FakeBestSellerResponse_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductResponse_7 extends _i1.SmartFake
    implements _i9.ProductResponse {
  _FakeProductResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoriesResponse_8 extends _i1.SmartFake
    implements _i10.CategoriesResponse {
  _FakeCategoriesResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeResponseDto_9 extends _i1.SmartFake
    implements _i11.HomeResponseDto {
  _FakeHomeResponseDto_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLogoutResponseDto_10 extends _i1.SmartFake
    implements _i12.LogoutResponseDto {
  _FakeLogoutResponseDto_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCartResponseDto_11 extends _i1.SmartFake
    implements _i13.CartResponseDto {
  _FakeCartResponseDto_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSuccessResponseDto_12 extends _i1.SmartFake
    implements _i14.SuccessResponseDto {
  _FakeSuccessResponseDto_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChangePasswordResponse_13 extends _i1.SmartFake
    implements _i15.ChangePasswordResponse {
  _FakeChangePasswordResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetUserDataResponse_14 extends _i1.SmartFake
    implements _i16.GetUserDataResponse {
  _FakeGetUserDataResponse_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadPhotoResponse_15 extends _i1.SmartFake
    implements _i17.UploadPhotoResponse {
  _FakeUploadPhotoResponse_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i18.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i2.LoginResponseDto> login({
    required _i20.LoginRequest? loginRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#loginRequest: loginRequest}),
            returnValue: _i19.Future<_i2.LoginResponseDto>.value(
              _FakeLoginResponseDto_0(
                this,
                Invocation.method(#login, [], {#loginRequest: loginRequest}),
              ),
            ),
          )
          as _i19.Future<_i2.LoginResponseDto>);

  @override
  _i19.Future<_i3.SignupResponse> signUp(_i21.UserSignupRequest? userRequest) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [userRequest]),
            returnValue: _i19.Future<_i3.SignupResponse>.value(
              _FakeSignupResponse_1(
                this,
                Invocation.method(#signUp, [userRequest]),
              ),
            ),
          )
          as _i19.Future<_i3.SignupResponse>);

  @override
  _i19.Future<_i4.SendResetPasswordCodeResponse> sendResetPasswordCode({
    required _i22.SendResetPasswordCodeRequest? sendResetPasswordCodeRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendResetPasswordCode, [], {
              #sendResetPasswordCodeRequest: sendResetPasswordCodeRequest,
            }),
            returnValue: _i19.Future<_i4.SendResetPasswordCodeResponse>.value(
              _FakeSendResetPasswordCodeResponse_2(
                this,
                Invocation.method(#sendResetPasswordCode, [], {
                  #sendResetPasswordCodeRequest: sendResetPasswordCodeRequest,
                }),
              ),
            ),
          )
          as _i19.Future<_i4.SendResetPasswordCodeResponse>);

  @override
  _i19.Future<_i5.VerifyResetCodeResponse> verifyResetPasswordCode({
    required _i23.VerifyResetCodeRequest? verifyResetCodeRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetPasswordCode, [], {
              #verifyResetCodeRequest: verifyResetCodeRequest,
            }),
            returnValue: _i19.Future<_i5.VerifyResetCodeResponse>.value(
              _FakeVerifyResetCodeResponse_3(
                this,
                Invocation.method(#verifyResetPasswordCode, [], {
                  #verifyResetCodeRequest: verifyResetCodeRequest,
                }),
              ),
            ),
          )
          as _i19.Future<_i5.VerifyResetCodeResponse>);

  @override
  _i19.Future<_i6.ResetPasswordResponse> resetPassword({
    required _i24.ResetPasswordRequest? resetPasswordRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #resetPasswordRequest: resetPasswordRequest,
            }),
            returnValue: _i19.Future<_i6.ResetPasswordResponse>.value(
              _FakeResetPasswordResponse_4(
                this,
                Invocation.method(#resetPassword, [], {
                  #resetPasswordRequest: resetPasswordRequest,
                }),
              ),
            ),
          )
          as _i19.Future<_i6.ResetPasswordResponse>);

  @override
  _i19.Future<_i7.GetCurrentUserDataResponseDto> getCurrentUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUserData, []),
            returnValue: _i19.Future<_i7.GetCurrentUserDataResponseDto>.value(
              _FakeGetCurrentUserDataResponseDto_5(
                this,
                Invocation.method(#getCurrentUserData, []),
              ),
            ),
          )
          as _i19.Future<_i7.GetCurrentUserDataResponseDto>);

  @override
  _i19.Future<_i8.BestSellerResponse> getBestSeller() =>
      (super.noSuchMethod(
            Invocation.method(#getBestSeller, []),
            returnValue: _i19.Future<_i8.BestSellerResponse>.value(
              _FakeBestSellerResponse_6(
                this,
                Invocation.method(#getBestSeller, []),
              ),
            ),
          )
          as _i19.Future<_i8.BestSellerResponse>);

  @override
  _i19.Future<_i9.ProductResponse> getProducts({
    String? occasionId,
    String? categoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {
              #occasionId: occasionId,
              #categoryId: categoryId,
            }),
            returnValue: _i19.Future<_i9.ProductResponse>.value(
              _FakeProductResponse_7(
                this,
                Invocation.method(#getProducts, [], {
                  #occasionId: occasionId,
                  #categoryId: categoryId,
                }),
              ),
            ),
          )
          as _i19.Future<_i9.ProductResponse>);

  @override
  _i19.Future<_i10.CategoriesResponse> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i19.Future<_i10.CategoriesResponse>.value(
              _FakeCategoriesResponse_8(
                this,
                Invocation.method(#getCategories, []),
              ),
            ),
          )
          as _i19.Future<_i10.CategoriesResponse>);

  @override
  _i19.Future<_i11.HomeResponseDto> fetchHomeData() =>
      (super.noSuchMethod(
            Invocation.method(#fetchHomeData, []),
            returnValue: _i19.Future<_i11.HomeResponseDto>.value(
              _FakeHomeResponseDto_9(
                this,
                Invocation.method(#fetchHomeData, []),
              ),
            ),
          )
          as _i19.Future<_i11.HomeResponseDto>);

  @override
  _i19.Future<_i12.LogoutResponseDto> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i19.Future<_i12.LogoutResponseDto>.value(
              _FakeLogoutResponseDto_10(this, Invocation.method(#logout, [])),
            ),
          )
          as _i19.Future<_i12.LogoutResponseDto>);

  @override
  _i19.Future<_i13.CartResponseDto> addProductToCart(
    _i25.CartRequestDto? cartRequestDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addProductToCart, [cartRequestDto]),
            returnValue: _i19.Future<_i13.CartResponseDto>.value(
              _FakeCartResponseDto_11(
                this,
                Invocation.method(#addProductToCart, [cartRequestDto]),
              ),
            ),
          )
          as _i19.Future<_i13.CartResponseDto>);

  @override
  _i19.Future<_i13.CartResponseDto> removeProductFromCart(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeProductFromCart, [id]),
            returnValue: _i19.Future<_i13.CartResponseDto>.value(
              _FakeCartResponseDto_11(
                this,
                Invocation.method(#removeProductFromCart, [id]),
              ),
            ),
          )
          as _i19.Future<_i13.CartResponseDto>);

  @override
  _i19.Future<_i14.SuccessResponseDto> clearCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, []),
            returnValue: _i19.Future<_i14.SuccessResponseDto>.value(
              _FakeSuccessResponseDto_12(
                this,
                Invocation.method(#clearCart, []),
              ),
            ),
          )
          as _i19.Future<_i14.SuccessResponseDto>);

  @override
  _i19.Future<_i13.CartResponseDto> getLoggedUserCart() =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedUserCart, []),
            returnValue: _i19.Future<_i13.CartResponseDto>.value(
              _FakeCartResponseDto_11(
                this,
                Invocation.method(#getLoggedUserCart, []),
              ),
            ),
          )
          as _i19.Future<_i13.CartResponseDto>);

  @override
  _i19.Future<_i13.CartResponseDto> updateProductQuantity(
    String? id,
    Map<String, int>? quantity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProductQuantity, [id, quantity]),
            returnValue: _i19.Future<_i13.CartResponseDto>.value(
              _FakeCartResponseDto_11(
                this,
                Invocation.method(#updateProductQuantity, [id, quantity]),
              ),
            ),
          )
          as _i19.Future<_i13.CartResponseDto>);

  @override
  _i19.Future<_i15.ChangePasswordResponse> changePassword(
    _i26.ChangePasswordRequest? changePasswordRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [changePasswordRequest]),
            returnValue: _i19.Future<_i15.ChangePasswordResponse>.value(
              _FakeChangePasswordResponse_13(
                this,
                Invocation.method(#changePassword, [changePasswordRequest]),
              ),
            ),
          )
          as _i19.Future<_i15.ChangePasswordResponse>);

  @override
  _i19.Future<_i16.GetUserDataResponse> getProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, []),
            returnValue: _i19.Future<_i16.GetUserDataResponse>.value(
              _FakeGetUserDataResponse_14(
                this,
                Invocation.method(#getProfileData, []),
              ),
            ),
          )
          as _i19.Future<_i16.GetUserDataResponse>);

  @override
  _i19.Future<_i16.GetUserDataResponse> editProfile({
    required _i27.EditProfileRequest? editProfileRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [], {
              #editProfileRequest: editProfileRequest,
            }),
            returnValue: _i19.Future<_i16.GetUserDataResponse>.value(
              _FakeGetUserDataResponse_14(
                this,
                Invocation.method(#editProfile, [], {
                  #editProfileRequest: editProfileRequest,
                }),
              ),
            ),
          )
          as _i19.Future<_i16.GetUserDataResponse>);

  @override
  _i19.Future<_i17.UploadPhotoResponse> uploadPhoto(
    _i28.MultipartFile? photo,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadPhoto, [photo]),
            returnValue: _i19.Future<_i17.UploadPhotoResponse>.value(
              _FakeUploadPhotoResponse_15(
                this,
                Invocation.method(#uploadPhoto, [photo]),
              ),
            ),
          )
          as _i19.Future<_i17.UploadPhotoResponse>);
}
