// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/auth/presentation/cubit/forget_password/forget_password_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_app/core/error_handling/result.dart' as _i4;
import 'package:flower_app/features/auth/data/models/requesets/reset_password_request.dart'
    as _i6;
import 'package:flower_app/features/auth/data/models/requesets/send_reset_password_code_request.dart'
    as _i10;
import 'package:flower_app/features/auth/data/models/requesets/verify_reset_code_request.dart'
    as _i13;
import 'package:flower_app/features/auth/data/models/response/reset_password_response.dart'
    as _i5;
import 'package:flower_app/features/auth/data/models/response/send_reset_password_code_response.dart'
    as _i9;
import 'package:flower_app/features/auth/data/models/response/verify_reset_code_response.dart'
    as _i12;
import 'package:flower_app/features/auth/domain/use_cases/forget_password/reset_password_use_case.dart'
    as _i2;
import 'package:flower_app/features/auth/domain/use_cases/forget_password/send_reset_password_code_use_case.dart'
    as _i8;
import 'package:flower_app/features/auth/domain/use_cases/forget_password/verify_reset_password_code_use_case.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i2.ResetPasswordUseCase {
  MockResetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.ResetPasswordResponse>> call({
    required _i6.ResetPasswordRequest? resetPasswordRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #resetPasswordRequest: resetPasswordRequest,
            }),
            returnValue:
                _i3.Future<_i4.Result<_i5.ResetPasswordResponse>>.value(
                  _i7.dummyValue<_i4.Result<_i5.ResetPasswordResponse>>(
                    this,
                    Invocation.method(#call, [], {
                      #resetPasswordRequest: resetPasswordRequest,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.ResetPasswordResponse>>);
}

/// A class which mocks [SendResetPasswordCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendResetPasswordCodeUseCase extends _i1.Mock
    implements _i8.SendResetPasswordCodeUseCase {
  MockSendResetPasswordCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i9.SendResetPasswordCodeResponse>> call({
    required _i10.SendResetPasswordCodeRequest? sendResetPasswordCodeRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #sendResetPasswordCodeRequest: sendResetPasswordCodeRequest,
            }),
            returnValue:
                _i3.Future<_i4.Result<_i9.SendResetPasswordCodeResponse>>.value(
                  _i7.dummyValue<_i4.Result<_i9.SendResetPasswordCodeResponse>>(
                    this,
                    Invocation.method(#call, [], {
                      #sendResetPasswordCodeRequest:
                          sendResetPasswordCodeRequest,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i9.SendResetPasswordCodeResponse>>);
}

/// A class which mocks [VerifyResetPasswordCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyResetPasswordCodeUseCase extends _i1.Mock
    implements _i11.VerifyResetPasswordCodeUseCase {
  MockVerifyResetPasswordCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i12.VerifyResetCodeResponse>> call({
    required _i13.VerifyResetCodeRequest? verifyResetCodeRequest,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #verifyResetCodeRequest: verifyResetCodeRequest,
            }),
            returnValue:
                _i3.Future<_i4.Result<_i12.VerifyResetCodeResponse>>.value(
                  _i7.dummyValue<_i4.Result<_i12.VerifyResetCodeResponse>>(
                    this,
                    Invocation.method(#call, [], {
                      #verifyResetCodeRequest: verifyResetCodeRequest,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i12.VerifyResetCodeResponse>>);
}
