// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/auth/presentation/cubit/forget_password/forget_password_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_app/core/error_handling/result.dart' as _i4;
import 'package:flower_app/features/auth/data/models/response/reset_password_response.dart'
    as _i5;
import 'package:flower_app/features/auth/data/models/response/send_reset_password_code_response.dart'
    as _i8;
import 'package:flower_app/features/auth/data/models/response/verify_reset_code_response.dart'
    as _i10;
import 'package:flower_app/features/auth/domain/use_cases/forget_password/reset_password_use_case.dart'
    as _i2;
import 'package:flower_app/features/auth/domain/use_cases/forget_password/send_reset_password_code_use_case.dart'
    as _i7;
import 'package:flower_app/features/auth/domain/use_cases/forget_password/verify_reset_password_code_use_case.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i2.ResetPasswordUseCase {
  MockResetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.ResetPasswordResponse>> call({
    required String? email,
    dynamic password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#email: email, #password: password}),
            returnValue:
                _i3.Future<_i4.Result<_i5.ResetPasswordResponse>>.value(
                  _i6.dummyValue<_i4.Result<_i5.ResetPasswordResponse>>(
                    this,
                    Invocation.method(#call, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.ResetPasswordResponse>>);
}

/// A class which mocks [SendResetPasswordCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendResetPasswordCodeUseCase extends _i1.Mock
    implements _i7.SendResetPasswordCodeUseCase {
  MockSendResetPasswordCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i8.SendResetPasswordCodeResponse>> call({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#email: email}),
            returnValue:
                _i3.Future<_i4.Result<_i8.SendResetPasswordCodeResponse>>.value(
                  _i6.dummyValue<_i4.Result<_i8.SendResetPasswordCodeResponse>>(
                    this,
                    Invocation.method(#call, [], {#email: email}),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i8.SendResetPasswordCodeResponse>>);
}

/// A class which mocks [VerifyResetPasswordCodeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyResetPasswordCodeUseCase extends _i1.Mock
    implements _i9.VerifyResetPasswordCodeUseCase {
  MockVerifyResetPasswordCodeUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i10.VerifyResetCodeResponse>> call({
    required String? resetCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#resetCode: resetCode}),
            returnValue:
                _i3.Future<_i4.Result<_i10.VerifyResetCodeResponse>>.value(
                  _i6.dummyValue<_i4.Result<_i10.VerifyResetCodeResponse>>(
                    this,
                    Invocation.method(#call, [], {#resetCode: resetCode}),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i10.VerifyResetCodeResponse>>);
}
