name: Firebase App Distribution (On Label)

on:
  pull_request:
    branches: [ "development" ]
    types: [labeled, synchronize]

jobs:
  android:
    if: contains(github.event.pull_request.labels.*.name, 'ReadyForTesting')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: flutter build apk --debug

      - name: Upload Android to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: appdistribution:distribute build/app/outputs/flutter-apk/app-debug.apk --app ${{ secrets.FIREBASE_APP_ID }} --groups "testers"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  ios:
    if: contains(github.event.pull_request.labels.*.name, 'ReadyForTesting')
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      
      # بناء للـ Simulator لتجنب مشاكل الشهادات والتوقيع
      - name: Build iOS for Simulator
        run: flutter build ios --debug --simulator

      - name: Zip iOS Bundle
        run: |
          cd build/ios/iphonesimulator
          zip -r Runner.zip Runner.app
          cd ../../..

      - name: Upload iOS to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: appdistribution:distribute build/ios/iphonesimulator/Runner.zip --app ${{ secrets.FIREBASE_IOS_APP_ID }} --groups "testers"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}