name: Firebase Distribution

on:
  pull_request:
    types: [labeled, synchronize]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'ReadyForTesting')
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK (Android)
        run: flutter build apk --debug
        env:
          # هنا بنحقن الـ Key من خزنة GitHub للـ Android
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}

      - name: Build iOS
        run: flutter build ios --debug --no-codesign

      - name: Upload to Firebase Distribution
        uses: w9jds/firebase-action@master
        with:
          args: appdistribution:distribute build/app/outputs/flutter-apk/app-debug.apk --app ${{ secrets.FIREBASE_APP_ID_ANDROID }} --groups "testers"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}